### ISSUE TITLE
Error on first run, my keys inserted for the demo values

### ISSUE THREAD

**Issue by rus19023** [shrimpy-dev/shrimpy-python#1]
sorry if I am doing this wrong, it's my first time reporting an issue with github.

After substituting my own keys for what the demo provided, and running the script, I get this output: 

python3.8 "/home/.../shrimpy.py"
Traceback (most recent call last):
  File "/home/...y/shrimpy.py", line 1, in <module>
    import shrimpy
  File "/home/.../shrimpy.py", line 7, in <module>
    client = shrimpy.ShrimpyApiClient(public_key, secret_key)
AttributeError: partially initialized module 'shrimpy' has no attribute 'ShrimpyApiClient' (most likely due to a circular import)

Searching for the error did not give me anything I could understand. My intention here is to practice and expand my newly acquired noob skill using python for data science with data that interests my son, who is a noob cryptocoin investor.  (I have just begun my 3rd semester at BYU-I online seeking Applied Science degree) 

Thanks in advance for any help!

-Doris

**Comment by noahwoodin** [comment]
Did you ever figure this out?
