### ISSUE TITLE
asyncio.Task.all_tasks() => asyncio.all_tasks()

### ISSUE THREAD

**Issue by bryantbrock** [shrimpy-dev/shrimpy-python#10]
Hi - I am having an error when I try using the websocket functionality. Below is the code I am running (used in your readme), and am getting an asyncio error, one that has been solved for [other products](https://github.com/HackSoc/csbot/issues/174). Looks like you have a depreciated method call `asyncio.Task.all_tasks()` which should be `asyncio.all_tasks()`. Should be an easy update to the `shrimpy_ws_client.py` file, line 92.

```
client = shrimpy.ShrimpyApiClient(public_key, private_key)


# This is a sample handler, it simply prints the incoming message to the console
def error_handler(err):
    print(err)


# This is a sample handler, it simply prints the incoming message to the console
def handler(msg):
    print(msg)

raw_token = client.get_token()
ws_client = shrimpy.ShrimpyWsClient(error_handler, raw_token['token'])

subscribe_data = {
    "type": "subscribe",
    "exchange": "coinbasepro",
    "pair": "ltc-btc",
    "channel": "orderbook"
}

# Start processing the Shrimpy websocket stream!
ws_client.connect()
ws_client.subscribe(subscribe_data, handler)
```

**Comment by bryantbrock** [comment]
Needed to disconnect. Maybe worth looking into for the future as it is depreciated, but not an issue for runtime.

**Comment by gorkem2020** [comment]
I'm having the same issue. Did you solve it?

**Comment by bryantbrock** [comment]
@gorkem2020 make sure to call `ws_client.disconnect()` afterwards. If not, you will have the error. Looks like they need to update a function, but everything should work fine for you if you just close the connection after your start it.
