### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by armujahid** [shrimpy-dev/shrimpy-python#20]
Currently Shrimpy doesn't support Python 3.9. I am running v3.9.6 and I am getting this error
`AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'`
That's because `asyncio.Task.all_tasks()` is fully moved to `asyncio.all_tasks()` starting with 3.9
This has already reported at https://github.com/shrimpy-dev/shrimpy-python/issues/16 , https://github.com/shrimpy-dev/shrimpy-python/issues/10 and https://github.com/shrimpy-dev/shrimpy-python/issues/4

Even after changing `asyncio.Task.all_tasks():` to `asyncio.all_tasks():` in line 92 in "shrimpy_ws_client.py" I am getting this error 
`RuntimeError: no running event loop`

I will debug and will hopefully raise a backward compatible PR like https://github.com/jupyterhub/jupyterhub/pull/3298

**Comment by gorkem2020** [comment]
hello,

I had the same issue and fixed it. check the pull requests
