### ISSUE TITLE
Invalid Nonce Error for all authenticated endpoints 

### ISSUE THREAD

**Issue by mchavva1** [shrimpy-dev/shrimpy-python#21]
Hey folks, 
Just get started with shrimpy and I'm constantly getting "Invalid nonce" from all authentication end points when i use this client **_v0.0.15_**. 
I'm doing nothing fancy here but just test the basic endpoints such as `get_user()`, `list_accounts()` and `list_users()`.
Here's the screenshot. Is anyone else getting this error?
![image](https://user-images.githubusercontent.com/10067793/137649385-00286566-e24b-4fe8-85be-3e830dde1ca9.png)

I'm actually getting 200 when i hit the endpoints directly from postman. Can someone comment on this?
![image](https://user-images.githubusercontent.com/10067793/137649324-bdf51579-7529-459a-9ce0-73cf36eed9d0.png)

**Comment by mchavva1** [comment]
I'm facing the same issue with shrimpy-node client as well. I tried to convert the nonce to a string value in the python client and yet I'm getting the "Invalid nonce" error.

![image](https://user-images.githubusercontent.com/10067793/137827470-45824e48-afc5-48b5-8450-9249b71c9cfe.png)

**Comment by vinhloc30796** [comment]
@mchavva1 how did you generate the signature for the Postman test? Perhaps we can replicate that in Python & retry?
