### ISSUE TITLE
Trouble getting Users  users:  {'error': 'Invalid IP address, API Key, or signature'}

### ISSUE THREAD

**Issue by atka007** [shrimpy-dev/shrimpy-python#23]
I am using this code:

import shrimpy
public_key = 'xxxxxx'
secret_key = 'xxxxxxxx'
client = shrimpy.ShrimpyApiClient(public_key, secret_key)
users = client.list_users()
print("\n users:  " + str(users))

Getting this error:

users:  {'error': 'Invalid IP address, API Key, or signature'}

I just generated ne API keys. What am I missing?

**Comment by vinhloc30796** [comment]
Same problems here as well!

**Comment by atka007** [comment]
Can we get any help on this?

**Comment by atka007** [comment]
I am still trying to get this working. I generated new API Keys again.
I am getting response for "supported_exchanges" and "ticker" but for the "users" I am still getting the error:
 users:  {'error': 'Invalid IP address, API Key, or signature'}

Did anyone get this working recently. Developers PLEASE HELP!

See my code below:


import shrimpy

public_key = 'xxxxxx'
secret_key = 'xxxxxxxxxx'

client = shrimpy.ShrimpyApiClient(public_key, secret_key)
#alloc = shrimpy.allocation()

supported_exchanges = client.get_supported_exchanges()
print("\n supported_exchanges:  " + str(supported_exchanges))

ticker = client.get_ticker('binanceus')
print("\n ticker:  " + str(ticker))  #Get all Coin data on Binance

users = client.list_users()
print("\n users:  " + str(users))

**Comment by vinhloc30796** [comment]
@atka007 I'm not Shrimpy team, but are you using the API key from [https://dashboard.shrimpy.io/](https://dashboard.shrimpy.io/) or are you using the key from [https://developers.shrimpy.io/dashboard/](https://developers.shrimpy.io/dashboard/)? Because only the latter works. I don't know what the API key of the former is used for lolol

**Comment by atka007** [comment]
HAHAH this whole time I thought I need the API for my trading account. 
Using the Dev Account API keys works. Thank you very much. I wish that was clearer in the Doc.

**Comment by ehelenowski** [comment]
https://developers.shrimpy.io/dashboard/ now redirects to https://help.shrimpy.io/hc/en-us/articles/4412537448219-Shrimpy-Developer-API-Shutdown . Given the URL of the redirect (which I can't view due to some weird access issue)- is the API no longer existent?
