### ISSUE TITLE
AttributeError: module 'shrimpy' has no attribute 'ShrimpyApiClient'

### ISSUE THREAD

**Issue by TekpreXyz** [shrimpy-dev/shrimpy-python#3]
Traceback (most recent call last):
  File "C:////PycharmProjects/pythonProject/main.py", line 30, in <module>
    client = shrimpy.ShrimpyApiClient(public_key, secret_key)
AttributeError: module 'shrimpy' has no attribute 'ShrimpyApiClient'

import shrimpy
import plotly.graph_objects as go
public_key = '
secret_key = 
client = shrimpy.ShrimpyApiClient(public_key, secret_key)

**Comment by NubeBuster** [comment]
bump

**Comment by lratjens** [comment]
Suggest you double check you've installed the correct package, 'shrimpy-python' not 'shrimpy'.
